[[pages]]
path = "Tag.py"
name = "Tags Management"
icon = "ğŸ·ï¸"


[[pages]]
path = "pages/Create_Rule.py"
name = "Create Tag Rule"
icon = "âš™ï¸"

[[pages]]
path = "pages/Shares_Management.py"
name = "Shares Management"
icon = "ğŸ”—"


[[pages]]
path = "pages/Warehouse_management.py"
name = "Warehouse Management"
icon = "ğŸ¬"


[[pages]]
path = "pages/Alert_Management.py"
name = "Alert Management"
icon = "â³"


[[pages]]
path = "pages/Settings.py"
name = "App Settings"
icon = "âš™ï¸"